import { test, expect } from '@playwright/test';

test.use({ channel: 'chrome', viewport: { width: 1500, height: 1100 } });
test('full-screen authoring completes Core syntax and reports recoverable source and SQL errors', async ({ page }) => {
  test.setTimeout(180_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('evidence/reports');
  const panel = page.getByTestId('evidence-panel');
  await panel.getByRole('button', { name: 'New report', exact: true }).click();
  await panel.getByRole('tab', { name: 'Code', exact: true }).click();
  const source = panel.getByRole('textbox', { name: 'Evidence source', exact: true });
  await expect(source).toBeVisible({ timeout: 90_000 });
  await expect(panel.getByRole('button', { name: 'Update preview', exact: true })).toBeEnabled({ timeout: 90_000 });
  await expect(panel.getByRole('link', { name: 'Evidence docs ↗', exact: true })).toHaveAttribute('href', /core-concepts\/markdown/);
  await expect(panel.getByRole('link', { name: 'Component reference ↗', exact: true })).toHaveAttribute('target', '_blank');
  await page.evaluate(() => { (window as any).__authoringWorker = (window as any).__bridge.worker; });
  const divider = panel.getByRole('separator', { name: 'Resize report editor' });
  const editor = panel.getByRole('complementary', { name: 'Report editor', exact: true });
  const beforeResize = await editor.evaluate(el => el.getBoundingClientRect().width);
  const handle = (await divider.boundingBox())!;
  await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
  await page.mouse.down();
  await page.mouse.move(handle.x - 150, handle.y + handle.height / 2, { steps: 8 });
  await page.mouse.up();
  expect(await editor.evaluate(el => el.getBoundingClientRect().width)).toBeGreaterThan(beforeResize + 100);
  await divider.focus();
  const draggedWidth = Number(await divider.getAttribute('aria-valuenow'));
  await divider.press('ArrowLeft');
  expect(Number(await divider.getAttribute('aria-valuenow'))).toBe(draggedWidth + 2);
  await panel.getByRole('button', { name: 'View report', exact: true }).click();
  await expect(divider).toHaveCount(0);
  await panel.getByRole('button', { name: 'Edit report', exact: true }).click();
  expect(Number(await divider.getAttribute('aria-valuenow'))).toBe(draggedWidth + 2);
  await divider.dblclick();
  await expect(divider).toHaveAttribute('aria-valuenow', '36');
  await panel.getByRole('button', { name: 'Full-screen editor', exact: true }).click();
  await expect(panel.getByRole('region', { name: 'Report preview', exact: true })).not.toBeVisible();
  expect(await panel.getByRole('complementary', { name: 'Report editor', exact: true }).evaluate(el => el.getBoundingClientRect().width)).toBeGreaterThan(1400);
  await source.fill('{% line_ch');
  await source.press('Control+Space');
  await expect(page.getByRole('option', { name: 'line_chart', exact: true })).toBeVisible();
  // Clicking avoids CodeMirror's short keyboard interaction guard immediately after opening.
  await page.getByRole('option', { name: 'line_chart', exact: true }).click();
  await expect(source).toContainText('{% line_chart');
  await source.fill('{% line_chart dat');
  await source.press('Control+Space');
  await expect(page.getByRole('option', { name: /data/ }).first()).toBeVisible();
  await source.press('Escape');
  await expect(panel.getByRole('button', { name: 'Exit full-screen editor', exact: true })).toBeVisible();
  const valid = '# Authoring test\n\n```sql example\nSELECT 12 AS value\n```\n\n{% big_value data="example" value="sum(value)" /%}';
  await source.fill(valid + '\n\n{% not_a_component /%}');
  await source.press('Control+Enter');
  const problems = panel.getByRole('region', { name: 'Report problems', exact: true });
  await expect(problems).toContainText('not_a_component', { timeout: 30_000 });
  const issue = problems.getByRole('button').filter({ hasText: 'not_a_component' }).first();
  await expect(issue).toContainText('line 9');
  await issue.click();
  await expect(source).toBeFocused();
  await expect(panel.locator('.cm-lintRange-error').first()).toBeVisible();
  await source.fill(valid);
  await expect(problems).toContainText('previous preview');
  await source.press('Control+Enter');
  await expect(problems).toContainText('Problems · 0', { timeout: 30_000 });
  await panel.getByRole('button', { name: 'Show preview', exact: true }).click();
  await expect(panel.getByTestId('evidence-document')).toContainText('12');
  await source.fill('# Broken query\n\n```sql missing\nSELECT * FROM cupola_table_that_does_not_exist\n```\n\n{% table data="missing" /%}');
  await source.press('Control+Enter');
  await expect(problems).toContainText('cupola_table_that_does_not_exist', { timeout: 30_000 });
  await expect(problems.getByText('Failed SQL').first()).toBeVisible();
  await source.fill(valid);
  await source.press('Control+Enter');
  await expect(panel.getByTestId('evidence-document')).toContainText('12');
  await expect(problems).toContainText('Problems · 0');
  await panel.getByRole('tab', { name: 'Data', exact: true }).click();
  const data = panel.getByRole('textbox', { name: 'Dataset SQL', exact: true });
  await data.fill('SELECT * FROM missing_setup_table');
  await data.press('Control+Enter');
  await expect(problems).toContainText('Data · error:', { timeout: 30_000 });
  await data.fill('');
  await data.press('Control+Enter');
  await expect(panel.getByTestId('evidence-document')).toContainText('12');
  await expect(problems).toContainText('Problems · 0');
  expect(await page.evaluate(() => (window as any).__authoringWorker === (window as any).__bridge.worker)).toBe(true);
  expect(errors).toEqual([]);
});
