import { test, expect } from '@playwright/test';

test.use({ channel: 'chrome', viewport: { width: 1500, height: 1100 } });
test('data browser previews setup tables and dependent parameterized queries using the existing engine', async ({ page }) => {
  test.setTimeout(180_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('evidence/reports');
  const panel = page.getByTestId('evidence-panel');
  await panel.getByRole('button', { name: 'New report', exact: true }).click();
  await expect(panel.getByRole('button', { name: 'Update preview', exact: true })).toBeEnabled({ timeout: 90_000 });
  await page.evaluate(() => { (window as any).__dataBrowserWorker = (window as any).__bridge.worker; });
  await panel.getByRole('tab', { name: 'Parameters', exact: true }).click();
  await panel.getByRole('button', { name: 'Add parameter' }).click();
  await panel.getByLabel('Parameter 1 default', { exact: true }).fill('hello');
  await panel.getByRole('tab', { name: 'Data', exact: true }).click();
  await panel.getByRole('textbox', { name: 'Dataset SQL', exact: true }).fill('CREATE OR REPLACE TEMP TABLE browser_test AS SELECT range AS value FROM range(150)');
  await panel.getByRole('tab', { name: 'Code', exact: true }).click();
  const source = panel.getByRole('textbox', { name: 'Evidence source', exact: true });
  const definition = '# Browser test\n\n```sql base\nSELECT *, $parameter_1 AS greeting FROM browser_test\n```\n\n```sql dependent\nSELECT * FROM {{base}} WHERE value < 2\n```\n\n```sql empty\nSELECT * FROM browser_test WHERE false\n```\n\n```sql broken\nSELECT * FROM nonexistent_browser_table\n```';
  await source.fill(definition);
  await panel.getByRole('tab', { name: 'Browse data', exact: true }).click();
  const browser = panel.getByRole('region', { name: 'Data browser', exact: true });
  await browser.getByRole('button', { name: 'Update data', exact: true }).click();
  const select = browser.getByLabel('Browse dataset', { exact: true });
  await expect(select.locator('option[value="query:dependent"]')).toHaveCount(1, { timeout: 30_000 });
  await select.selectOption('query:dependent');
  await browser.getByRole('button', { name: 'Preview rows' }).click();
  await expect(browser.getByRole('status', { name: 'Dataset preview result' })).toContainText('2 rows');
  await expect(browser.getByRole('cell', { name: 'hello', exact: true })).toHaveCount(2);
  await browser.getByText('Columns and types (2)', { exact: true }).click();
  await expect(browser).toContainText('Int64');
  const tableOption = select.locator('option').filter({ hasText: /\.browser_test$/ });
  await expect(tableOption).toHaveCount(1);
  await select.selectOption((await tableOption.getAttribute('value'))!);
  await browser.getByRole('button', { name: 'Preview rows' }).click();
  await expect(browser.getByRole('status', { name: 'Dataset preview result' })).toContainText('Showing first 100 rows');
  await expect(browser.getByRole('row')).toHaveCount(101);
  await select.selectOption('query:empty');
  await browser.getByRole('button', { name: 'Preview rows' }).click();
  await expect(browser).toContainText('This dataset returned no rows');
  await expect(browser).toContainText('Columns and types (1)');
  await select.selectOption('query:broken');
  await browser.getByRole('button', { name: 'Preview rows' }).click();
  await expect(browser.getByRole('alert')).toContainText('nonexistent_browser_table');
  await panel.getByRole('tab', { name: 'Code', exact: true }).click();
  await source.fill(definition.replace('value < 2', 'value < 3'));
  await panel.getByRole('tab', { name: 'Browse data', exact: true }).click();
  await select.selectOption('query:dependent');
  await expect(browser.getByRole('button', { name: 'Preview rows' })).toBeDisabled();
  await browser.getByRole('button', { name: 'Update data', exact: true }).click();
  await expect(browser.getByRole('button', { name: 'Preview rows' })).toBeEnabled();
  await browser.getByRole('button', { name: 'Preview rows' }).click();
  await expect(browser.getByRole('status', { name: 'Dataset preview result' })).toContainText('3 rows');
  expect(await page.evaluate(() => (window as any).__dataBrowserWorker === (window as any).__bridge.worker)).toBe(true);
  expect(errors).toEqual([]);
});
