import { evidencePath } from './helpers';
import { test, expect } from '@playwright/test';

test.use({ viewport: { width: 1280, height: 900 } });
test('expanded tables remain visible, themed and keyboard accessible inside reports', async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(evidencePath('evidence/reports'));
  const panel = page.getByTestId('evidence-panel');
  await panel.getByRole('button', { name: 'New report', exact: true }).click();
  const report = panel.getByTestId('evidence-document');
  await expect(report.getByRole('cell', { name: '1.00', exact: true })).toBeVisible({ timeout: 60000 });
  const expand = report.getByRole('button', { name: 'Expand table', exact: true });
  await expand.click();
  const dialog = page.getByRole('dialog', { name: 'Table', exact: true });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('cell', { name: '1.00', exact: true })).toBeVisible();
  await expect(dialog).toBeInViewport();
  expect(await dialog.evaluate(el => el.getRootNode() instanceof ShadowRoot)).toBe(true);
  await dialog.getByRole('button', { name: 'Close expanded table' }).click();
  await expect(dialog).toHaveCount(0);
  await expect(expand).toBeFocused();
  await panel.getByRole('tab', { name: 'Appearance', exact: true }).click();
  await panel.getByLabel('Report theme', { exact: true }).selectOption('forest');
  await panel.getByLabel('Report color mode').selectOption('dark');
  await panel.getByRole('button', { name: 'View report', exact: true }).click();
  await panel.getByRole('button', { name: 'More report actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Focus report', exact: true }).click();
  await expand.click();
  await expect(dialog).toBeInViewport();
  await expect(dialog).toHaveCSS('background-color', 'rgb(23, 35, 27)');
  await dialog.getByRole('button', { name: 'Close expanded table' }).press('Escape');
  await expect(dialog).toHaveCount(0);
  await expect(panel.getByRole('button', { name: 'Exit focus mode', exact: true })).toBeVisible();
  await expect(expand).toBeFocused();
  await page.setViewportSize({ width: 390, height: 700 });
  await expand.click();
  await expect(dialog).toBeInViewport();
  expect((await dialog.boundingBox())!.width).toBeLessThan(390);
  await dialog.getByRole('button', { name: 'Exit fullscreen', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  expect(errors).toEqual([]);
});
