"""Generate the browser contract from the pinned worker SDK's real Python dataclasses.

Run with ../vgi-reporting-protocol-reference/.venv/bin/python scripts/generate-reporting-contracts.py
"""

import base64
import dataclasses
import datetime
import inspect
import json
import types
import typing
from pathlib import Path

from vgi.reporting import common, reports

records = [getattr(common, name) for name in (
    "PrincipalRef", "OwnerRef", "Ownership", "OwnershipInput", "ResourceMeta", "Ack", "Limit", "ServiceInfo",
    "DataSource", "ParameterOption", "ParameterSpec",
)] + [getattr(reports, name) for name in (
    "ReportEnvelope", "ReportRow", "ReportResult", "RevisionRow", "FolderRecord", "ReportsInfo",
)]


def unwrap(t):
    return unwrap(typing.get_args(t)[0]) if typing.get_origin(t) is typing.Annotated else t


def ts(t):
    t = unwrap(t)
    origin, args = typing.get_origin(t), typing.get_args(t)
    if origin in (typing.Union, types.UnionType):
        return " | ".join(ts(a) for a in args)
    if origin is typing.Literal:
        return " | ".join(json.dumps(a) for a in args)
    if origin is list:
        return f"Array<{ts(args[0])}>"
    return {str: "string", int: "bigint", bool: "boolean", bytes: "Uint8Array", type(None): "null",
            datetime.datetime: "number", float: "number"}.get(t, getattr(t, "__name__", "never"))


out = ["// Generated by scripts/generate-reporting-contracts.py. Do not edit.",
       '// SDK commit: 7b5301406bca63677ff61cdd58978b697046fa43',
       'export const REPORTS_PROTOCOL = "vgi.reports.v1";']
for record in records:
    hints = typing.get_type_hints(record, include_extras=True)
    out += [f"export interface {record.__name__} {{"]
    out += [f"  {field.name}: {ts(hints[field.name])};" for field in dataclasses.fields(record)]
    out += ["}"]

config = {}
streams = {"list_reports": "ReportRow", "list_folders": "FolderRecord", "list_revisions": "RevisionRow"}
out += ["export interface ReportMethods {"]
for name, method in inspect.getmembers(reports.ReportsProtocol, inspect.isfunction):
    if name.startswith("_"):
        continue
    hints = typing.get_type_hints(method, include_extras=True)
    signature = inspect.signature(method)
    defaults, structured, inputs = {}, {}, []
    for key, param in signature.parameters.items():
        if key == "self":
            continue
        optional = param.default is not inspect.Parameter.empty
        if optional:
            defaults[key] = param.default
        t = unwrap(hints[key])
        candidates = typing.get_args(t) if typing.get_origin(t) in (typing.Union, types.UnionType) else (t,)
        for candidate in candidates:
            if dataclasses.is_dataclass(candidate):
                structured[key] = candidate.__name__
        inputs.append(f"{key}{'?' if optional else ''}: {ts(t)}")
    result = streams.get(name, ts(hints["return"]))
    out += [f"  {name}: {{ input: {{ {'; '.join(inputs)} }}; output: {result}{'[]' if name in streams else ''} }};"]
    config[name] = dict(defaults=defaults, structured=structured, result=result, stream=name in streams)
out += ["}", "export const methodConfig = " + json.dumps(config, indent=2) + " as const;",
        "export const recordSchemas: Record<string, string> = " + json.dumps({
            r.__name__: base64.b64encode(r.ARROW_SCHEMA.serialize().to_pybytes()).decode() for r in records
        }, indent=2) + ";"]
Path("src/lib/reporting/contracts.generated.ts").write_text("\n".join(out) + "\n")
