"""Generate the browser contract from the pinned worker SDK's real Python dataclasses.

Run with ../vgi-reporting-protocol-reference/.venv/bin/python scripts/generate-reporting-contracts.py
"""

import base64
import dataclasses
import datetime
import inspect
import json
import types
import typing
from pathlib import Path

import pyarrow as pa
from vgi.reporting import common, reports, ownership, schedules, delegations, notify
from vgi.reporting._metadata import read_annotation
from vgi.attach_ticket import AttachTickets, SealAttachRequest, AttachTicket
from vgi_rpc.rpc._token_identity import Identity, IssuedGrant

records = list({record.__name__: record
    for module in (common, reports, ownership, schedules, delegations, notify)
    for record in vars(module).values()
    if isinstance(record, type) and dataclasses.is_dataclass(record) and hasattr(record, "ARROW_SCHEMA")
}.values()) + [IssuedGrant, SealAttachRequest, AttachTicket]


def unwrap(t):
    return unwrap(typing.get_args(t)[0]) if typing.get_origin(t) is typing.Annotated else t


def ts(t):
    t = unwrap(t)
    origin, args = typing.get_origin(t), typing.get_args(t)
    if origin in (typing.Union, types.UnionType):
        return " | ".join(ts(a) for a in args)
    if origin is typing.Literal:
        return " | ".join(json.dumps(a) for a in args)
    if origin is list:
        return f"Array<{ts(args[0])}>"
    return {str: "string", int: "bigint", bool: "boolean", bytes: "Uint8Array", type(None): "null",
            datetime.datetime: "number", float: "number", pa.RecordBatch: "Uint8Array"}.get(t, getattr(t, "__name__", "never"))


out = ["// Generated by scripts/generate-reporting-contracts.py. Do not edit.",
       '// Source: vgi-python reporting dataclasses, including inline HTML email contracts.',
       'export const REPORTS_PROTOCOL = "vgi.reports.v1";',
       'export const OWNERSHIP_PROTOCOL = "vgi.reports.ownership.v1";',
       'export const SCHEDULES_PROTOCOL = "vgi.schedules.v1";',
       'export const DELEGATIONS_PROTOCOL = "vgi.delegations.v1";',
       'export const NOTIFY_PROTOCOL = "vgi.notify.v1";']
for record in records:
    hints = typing.get_type_hints(record, include_extras=True)
    out += [f"export interface {record.__name__} {{"]
    out += [f"  {field.name}: {ts(hints[field.name])};" for field in dataclasses.fields(record)]
    out += ["}"]

config = {}
out += ["export interface ReportMethods {"]
protocols = [("", reports.ReportsProtocol), ("", ownership.ReportOwnershipProtocol),
             ("schedules.", schedules.SchedulesProtocol), ("delegations.", delegations.DelegationsProtocol),
             ("notify.", notify.NotifyProtocol), ("identity.", Identity), ("tickets.", AttachTickets)]
methods = [(prefix, p, name, method) for prefix, p in protocols
           for name, method in inspect.getmembers(p, inspect.isfunction)
           if (prefix != "identity." or name == "issue_grant") and (prefix != "notify." or name != "send")]
for prefix, protocol, name, method in methods:
    if name.startswith("_"):
        continue
    hints = typing.get_type_hints(method, include_extras=True)
    signature = inspect.signature(method)
    defaults, structured, inputs = {}, {}, []
    for key, param in signature.parameters.items():
        if key == "self":
            continue
        optional = param.default is not inspect.Parameter.empty
        if optional:
            defaults[key] = param.default
        t = unwrap(hints[key])
        candidates = typing.get_args(t) if typing.get_origin(t) in (typing.Union, types.UnionType) else (t,)
        for candidate in candidates:
            if dataclasses.is_dataclass(candidate):
                structured[key] = candidate.__name__
        inputs.append(f"{key}{'?' if optional else ''}: {ts(t)}")
    annotation = read_annotation(method)
    row = annotation.row_type if annotation else None
    result = row.__name__ if row else ts(hints["return"])
    key = prefix + name
    out += [f'  "{key}": {{ input: {{ {"; ".join(inputs)} }}; output: {result}{"[]" if row else ""} }};']
    config[key] = dict(name=name, protocol=protocol.protocol_name, defaults=defaults, structured=structured, result=result, stream=bool(row))
out += ["}", "export const methodConfig = " + json.dumps(config, indent=2) + " as const;",
        "export const recordSchemas: Record<string, string> = " + json.dumps({
            r.__name__: base64.b64encode(r.ARROW_SCHEMA.serialize().to_pybytes()).decode() for r in records
        }, indent=2) + ";"]
Path("src/lib/reporting/contracts.generated.ts").write_text("\n".join(out) + "\n")
