import type { ReportDocumentV1, ReportParameterValue } from './types';

export function escapeHtml(value: unknown): string {
  return String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
}
export interface SnapshotBlock { id: string; title: string; text?: string; image?: string; columns?: string[]; rows?: unknown[][]; totalRows?: number; fetchedAt?: number; status?: string }
/** Portable static document: only escaped text and generated PNGs, no scripts or remote resources. */
export function buildSnapshotHtml(report: ReportDocumentV1, values: Record<string, ReportParameterValue>, blocks: SnapshotBlock[], capturedAt = Date.now()): string {
  const e = escapeHtml;
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src data:; style-src 'unsafe-inline'"><title>${e(report.title)} — snapshot</title><style>body{font:15px/1.5 system-ui,sans-serif;color:#172033;background:#f5f6f8;margin:0}main{max-width:1100px;margin:auto;padding:32px}header,section{background:white;border:1px solid #dce1e8;border-radius:10px;padding:24px;margin-bottom:20px}h1,h2{margin-top:0}small,footer{color:#536174}.text{white-space:pre-wrap}img{max-width:100%;height:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{padding:8px;text-align:left;border-bottom:1px solid #ddd}.table{overflow:auto}@media print{body{background:white}main{padding:0}section{break-inside:avoid}}</style><main><header><h1>${e(report.title)}</h1><p>${e(report.description)}</p><p><strong>Frozen snapshot</strong> · Captured ${e(new Date(capturedAt).toLocaleString())}</p><small>This file contains captured results. It does not refresh or require a data connection.</small>${report.parameters.length ? `<p>${report.parameters.map(p => `${e(p.label)}: ${e(typeof values[p.key] === 'object' ? JSON.stringify(values[p.key]) : values[p.key] ?? p.defaultValue)}`).join(' · ')}</p>` : ''}</header>${blocks.map(block => `<section><h2>${e(block.title)}</h2>${block.fetchedAt ? `<small>Data fetched ${e(new Date(block.fetchedAt).toLocaleString())}${block.status && block.status !== 'success' ? ` · ${e(block.status)} — earlier results` : ''}</small>` : ''}${block.image?.startsWith('data:image/png;base64,') ? `<p><img alt="${e(block.title)}" src="${e(block.image)}"></p>` : ''}${block.text ? `<div class="text">${e(block.text)}</div>` : ''}${block.columns ? `<div class="table"><table><thead><tr>${block.columns.map(c => `<th>${e(c)}</th>`).join('')}</tr></thead><tbody>${(block.rows ?? []).map(row => `<tr>${row.map(value => `<td>${e(typeof value === 'object' && value !== null ? JSON.stringify(value) : value)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><small>${block.rows?.length ?? 0} of ${block.totalRows ?? block.rows?.length ?? 0} loaded rows included.</small>` : ''}</section>`).join('')}<footer>Captured from Cupola · Report revision ${e(report.revision)}</footer></main></html>`;
}
