import { describe, expect, test } from "bun:test";
import { parseDuckdbScript, tokenize, workspaceToDuckdbScript } from "../../src/lib/workspace/duckdb-script";
import type { ImportWorkspace } from "../../src/lib/workspace/file";
import type { Workspace, WorkspaceCatalog } from "../../src/lib/workspace/store";

let n = 0;
const newId = () => `gen${++n}`;

function catalog(c: Partial<WorkspaceCatalog> & Pick<WorkspaceCatalog, "id" | "url" | "catalogName" | "alias">): WorkspaceCatalog {
  return { options: {}, color: 0, enabled: true, ...c };
}

function workspace(over: Partial<Workspace> = {}): Workspace {
  return {
    id: "w1",
    name: "Finance",
    defaultCatalogId: "c1",
    defaultSchema: "main",
    createdAt: 0,
    updatedAt: 0,
    lastOpenedAt: 0,
    catalogs: [
      catalog({ id: "c1", url: "https://a.example/vgi", catalogName: "sales", alias: "sales", options: { region: "eu", note: "it's", limit: "5" } }),
      catalog({ id: "c2", url: "grainlift+https://gw.example", catalogName: "sqlite", alias: "gw", target: "sqlite" }),
    ],
    ...over,
  };
}

const secretNames = (_ws: Workspace, c: WorkspaceCatalog) => c.id === "c1" ? ["api_key", "pin"] : [];

function parsed(text: string): ImportWorkspace {
  const result = parseDuckdbScript(text, newId);
  if (!result.ok) throw new Error(result.errors.join("\n"));
  return result.workspace;
}

function errorsOf(text: string): string[] {
  const result = parseDuckdbScript(text, newId);
  if (result.ok) throw new Error("expected the script to be refused");
  return result.errors;
}

const ATTACH = "ATTACH 'sales' AS sales (TYPE vgi, LOCATION 'https://a.example')";

describe("export", () => {
  test("INSTALL/LOAD, one ATTACH per catalog with secrets as getenv(), then USE", () => {
    const script = workspaceToDuckdbScript(workspace(), secretNames);
    expect(script).toBe([
      "-- Cupola workspace: Finance",
      "-- Workspace id: w1",
      "-- Generated by Cupola. Run with: duckdb -init <this file>",
      "--",
      "-- Set these environment variables first:",
      "--   export SALES_API_KEY=...",
      "--   export SALES_PIN=...",
      "",
      "INSTALL vgi FROM community; LOAD vgi;",
      "INSTALL grainlift FROM community; LOAD grainlift;",
      "",
      "ATTACH 'sales' AS \"sales\" (TYPE vgi, LOCATION 'https://a.example/vgi', region 'eu', note 'it''s', limit '5', api_key getenv('SALES_API_KEY'), pin getenv('SALES_PIN'));",
      "ATTACH 'grainlift+https://gw.example' AS \"gw\" (TYPE grainlift, target 'sqlite');",
      "",
      "USE \"sales\".\"main\";",
      "",
    ].join("\n"));
  });

  test("only enabled catalogs are attached; no grainlift INSTALL without one; the default is the first enabled", () => {
    const ws = workspace({ defaultCatalogId: "c2", defaultSchema: null });
    ws.catalogs[1].enabled = false;
    const script = workspaceToDuckdbScript(ws);
    expect(script).not.toContain("grainlift FROM");
    expect(script).not.toContain("ATTACH 'grainlift");
    expect(script).toContain('--   "gw": disabled in this browser');
    expect(script).toContain('USE "sales";');
  });

  test("a name cannot break out of its comment", () => {
    const script = workspaceToDuckdbScript(workspace({ name: "x\nDROP TABLE t;\r\n--" }));
    expect(script.split("\n")[0]).toBe("-- Cupola workspace: x DROP TABLE t; --");
    expect(parseDuckdbScript(script, newId).ok).toBe(true);
  });

  test("pending raw options are named in a comment, never spliced in", () => {
    const ws = workspace();
    ws.catalogs[0].rawOptions = "evil (SELECT 1)";
    const script = workspaceToDuckdbScript(ws);
    expect(script).toContain("-- Not included for \"sales\": options not yet evaluated (evil (SELECT 1)).");
    expect(script).not.toMatch(/evil \(SELECT 1\)\)?;/);
  });

  test("a workspace with nothing to attach says so", () => {
    const ws = workspace();
    ws.catalogs.forEach((c) => { c.enabled = false; });
    expect(workspaceToDuckdbScript(ws)).toContain("-- This workspace has no catalog to attach.");
  });
});

describe("round trip", () => {
  test("script → spec → script is stable", () => {
    const first = workspaceToDuckdbScript(workspace(), secretNames);
    const item = parsed(first);
    const ws = item.workspace;
    expect(ws.id).toBe("w1");
    expect(ws.name).toBe("Finance");
    expect(ws.defaultSchema).toBe("main");
    expect(ws.defaultCatalogId).toBe(ws.catalogs[0].id);
    expect(ws.catalogs.map(({ id: _id, ...c }) => c)).toEqual([
      { url: "https://a.example/vgi", catalogName: "sales", alias: "sales", options: { region: "eu", note: "it's", limit: "5" }, secrets: ["api_key", "pin"] },
      { url: "grainlift+https://gw.example", catalogName: "sqlite", alias: "gw", target: "sqlite" },
    ]);
    expect(item.secretNotes?.[ws.catalogs[0].id]).toEqual({
      api_key: "read from the environment variable SALES_API_KEY in the script",
      pin: "read from the environment variable SALES_PIN in the script",
    });
    // Back to a stored workspace, and out again.
    const again: Workspace = {
      id: ws.id, name: ws.name ?? null, defaultCatalogId: ws.defaultCatalogId ?? null, defaultSchema: ws.defaultSchema ?? null,
      createdAt: 0, updatedAt: 0, lastOpenedAt: 0,
      catalogs: ws.catalogs.map((c) => catalog({ id: c.id, url: c.url, catalogName: c.catalogName, alias: c.alias!, options: c.options ?? {}, target: c.target })),
    };
    const secretsAgain = (_w: Workspace, c: WorkspaceCatalog) => ws.catalogs.find((x) => x.id === c.id)?.secrets ?? [];
    expect(workspaceToDuckdbScript(again, secretsAgain)).toBe(first);
  });

  test("data_version_spec round trips as the pinned version", () => {
    const ws = workspace();
    ws.catalogs[0].dataVersionSpec = "2024-06";
    const script = workspaceToDuckdbScript(ws);
    expect(script).toContain("data_version_spec '2024-06'");
    expect(parsed(script).workspace.catalogs[0].dataVersionSpec).toBe("2024-06");
  });
});

describe("import", () => {
  test("a hand-written script: comments, quoted names, flags, OR REPLACE, no header", () => {
    const item = parsed(`
      /* finance */
      -- the sales catalog
      ATTACH OR REPLACE DATABASE IF NOT EXISTS 'sales' AS "Sales_1" (
        TYPE VGI,            -- the extension
        LOCATION 'https://a.example',
        "region" 'eu',
        verbose,
        ratio -1.5,
        tags ['a', 'b'],
        start '2024-01-01'::DATE,
        cfg {'a': 1, 'b': [1, 2]}
      );
      USE "Sales_1";
    `);
    const ws = item.workspace;
    expect(ws.name).toBeNull();
    expect(ws.catalogs[0]).toMatchObject({ catalogName: "sales", alias: "Sales_1", options: { region: "eu", verbose: "true", ratio: "-1.5" } });
    expect(item.rawOptions?.[ws.catalogs[0].id]).toBe("tags ['a', 'b'], start '2024-01-01'::DATE, cfg {'a': 1, 'b': [1, 2]}");
    expect(ws.defaultCatalogId).toBe(ws.catalogs[0].id);
  });

  test("a literal credential is not imported; it becomes a secret to enter", () => {
    const result = parseDuckdbScript(`ATTACH 'sales' AS s (TYPE vgi, LOCATION 'https://a', api_key 'abc123');`, newId);
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(JSON.stringify(result.workspace)).not.toContain("abc123");
    expect(result.workspace.workspace.catalogs[0].secrets).toEqual(["api_key"]);
    expect(result.warnings.join(" ")).toContain("Line 1: api_key looks like a credential");
  });

  test("sign-in credentials are skipped", () => {
    const result = parseDuckdbScript(`ATTACH 'sales' AS s (TYPE vgi, LOCATION 'https://a', bearer_token getenv('T'));`, newId);
    expect(result.ok && result.workspace.workspace.catalogs[0].secrets).toBeFalsy();
    expect(result.ok && result.warnings.join(" ")).toContain("sign-in");
  });

  test("several catalogs, USE with a schema, default by alias", () => {
    const ws = parsed(`${ATTACH};\nATTACH 'b' AS b (TYPE vgi, LOCATION 'https://b');\nUSE b.reporting;`).workspace;
    expect(ws.catalogs.map((c) => c.alias)).toEqual(["sales", "b"]);
    expect(ws.defaultCatalogId).toBe(ws.catalogs[1].id);
    expect(ws.defaultSchema).toBe("reporting");
  });

  test("INSTALL/LOAD of vgi and grainlift are accepted and skipped", () => {
    expect(parseDuckdbScript(`INSTALL vgi; INSTALL vgi FROM community VERSION 'abc'; LOAD vgi; INSTALL grainlift FROM community; LOAD grainlift;\n${ATTACH};`, newId).ok).toBe(true);
  });
});

describe("refusals", () => {
  test("statements outside the accepted set, with line numbers", () => {
    expect(errorsOf(`${ATTACH};\nSET threads = 1;`)).toEqual([`Line 2: only ATTACH, USE, and INSTALL/LOAD of vgi or grainlift can be imported; "SET" is refused.`]);
    expect(errorsOf(`${ATTACH};\n\nPRAGMA x;\nSELECT 1;`)).toHaveLength(2);
    expect(errorsOf(`INSTALL httpfs;\n${ATTACH};`)[0]).toBe("Line 1: INSTALL is accepted only for the vgi and grainlift extensions.");
    expect(errorsOf(`LOAD 'evil.duckdb_extension';\n${ATTACH};`)[0]).toContain("Line 1:");
    expect(errorsOf(`${ATTACH};\nDETACH sales;`)[0]).toStartWith("Line 2:");
  });

  test("injection through a value stays a value, and the statement after it is refused", () => {
    // The quote is escaped: the option is the text `x'); DROP TABLE t; --`.
    const item = parsed(`ATTACH 'sales' AS s (TYPE vgi, LOCATION 'https://a', note 'x''); DROP TABLE t; --');`);
    expect(item.workspace.catalogs[0].options).toEqual({ note: "x'); DROP TABLE t; --" });
    // Unescaped, the ATTACH ends and DROP is its own statement.
    const errors = errorsOf(`ATTACH 'sales' AS s (TYPE vgi, LOCATION 'https://a', note 'x');\nDROP TABLE t;`);
    expect(errors).toEqual([`Line 2: only ATTACH, USE, and INSTALL/LOAD of vgi or grainlift can be imported; "DROP" is refused.`]);
    expect(errorsOf(`ATTACH 'sales' AS s (TYPE vgi, LOCATION 'https://a'), x;`)[0]).toContain('unexpected ","');
  });

  test("expressions that are not constants are refused", () => {
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v (SELECT 1));`)[0]).toBe('Line 1: v: "SELECT" is not allowed in an option value; only constants are.');
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v read_text('/etc/passwd'));`)[0]).toContain("read_text");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v current_setting('x'));`)[0]).toContain("current_setting(…)");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v 1 || 2);`)[0]).toContain('"|"');
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v "col");`)[0]).toContain("quoted name");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v upper(getenv('X')));`)[0]).toContain("getenv");
  });

  test("unbalanced quotes, brackets and comments", () => {
    expect(errorsOf(`ATTACH 'sales AS s (TYPE vgi);`)[0]).toBe("Line 1: a string is never closed (unbalanced ').");
    expect(errorsOf(`\n\nATTACH 's' AS "s (TYPE vgi);`)[0]).toBe('Line 3: a quoted name is never closed (unbalanced ").');
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', v [1, 2);`)[0]).toContain("unbalanced brackets");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a';`)[0]).toContain("not closed before the \";\"");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a'`)[0]).toContain("never closed");
    expect(errorsOf(`/* open\n${ATTACH};`)[0]).toBe("Line 1: a /* comment is never closed.");
    expect(errorsOf(`ATTACH $$s$$ AS s (TYPE vgi);`)[0]).toContain("unexpected character");
  });

  test("malformed ATTACH statements", () => {
    expect(errorsOf(`ATTACH 's' (TYPE vgi, LOCATION 'https://a');`)[0]).toContain("AS <name>");
    expect(errorsOf(`ATTACH 's' AS memory (TYPE vgi, LOCATION 'https://a');`)[0]).toContain("not a usable catalog alias");
    expect(errorsOf(`ATTACH 's' AS s (TYPE postgres, LOCATION 'https://a');`)[0]).toContain("only vgi and grainlift");
    expect(errorsOf(`ATTACH 's' AS s (LOCATION 'https://a');`)[0]).toContain("TYPE vgi");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi);`)[0]).toContain("LOCATION");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'file:///etc/passwd');`)[0]).toContain("http(s) or grainlift URL");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', x 1, x 2);`)[0]).toContain("given twice");
    expect(errorsOf(`ATTACH 's' AS s (TYPE vgi, LOCATION 'https://a', , x 1);`)[0]).toContain("empty entry");
    expect(errorsOf(`ATTACH 'grainlift+https://g' AS g (TYPE grainlift);`)[0]).toContain("target");
    expect(errorsOf(`ATTACH 'https://g' AS g (TYPE grainlift, target 'x');`)[0]).toContain("grainlift:// URL");
    expect(errorsOf(`${ATTACH};\n${ATTACH};`)[0]).toBe('Line 2: the alias "sales" is already used on line 1.');
    expect(errorsOf(`${ATTACH};\nUSE other;`)[0]).toContain("does not attach");
    expect(errorsOf(`-- nothing here`)[0]).toContain("attaches no catalog");
  });
});

describe("tokenizer", () => {
  test("strings, quoted identifiers, numbers, :: and line numbers", () => {
    const tokens = tokenize(`'it''s' "a""b"\n 1.5e-3 x::DATE -- c\n/* d */ ;`);
    expect(tokens.map((t) => [t.type, t.value, t.line])).toEqual([
      ["string", "it's", 1], ["qident", 'a"b', 1], ["number", "1.5e-3", 2], ["ident", "x", 2], ["punct", "::", 2], ["ident", "DATE", 2], ["punct", ";", 3],
    ]);
  });
});
