/**
 * A workspace as a DuckDB script, and back.
 *
 * Export (`workspaceToDuckdbScript`): the extensions' INSTALL/LOAD, one ATTACH
 * per enabled catalog, built by `buildAttachSql` in `cli` mode (the same
 * builder the engine uses, so secrets become `getenv('<ALIAS>_<OPTION>')`
 * and nothing is quoted differently), then `USE "alias"."schema"`. A header
 * comment names the workspace, its id, and the environment variables to set.
 *
 * Import (`parseDuckdbScript`): a script is untrusted text, so the parser
 * accepts a closed set and refuses the rest, line-numbered:
 *
 * - `ATTACH [OR REPLACE] [DATABASE] [IF NOT EXISTS] '<path>' [AS] <ident>
 *   (TYPE vgi|grainlift, LOCATION '<url>', <opt> <value>, …)`
 * - `USE <ident>[.<ident>]`
 * - `INSTALL`/`LOAD` of vgi or grainlift only (what an export writes; they
 *   carry nothing and are skipped). `SET`, `PRAGMA`, other extensions and
 *   every other statement are refused.
 *
 * Option values go through the same rules as the legacy option text
 * (`attach/legacy-options.ts`): plain literals convert here; any other
 * constant expression is kept as raw option text, which the engine checks
 * against the constant allowlist at connect time before it runs (and which a
 * static screen here refuses early when it names a query or a function
 * outside the allowlist). `getenv('X')` makes the option a secret with no
 * value, noted with X. A literal secret in a script is not imported.
 *
 * Pure: unit-tested in tests/unit/workspace-duckdb-script.test.ts.
 */
import { quoteIdent } from "../duckdb-query";
import { extensionInstallSql, SHELL_EXTENSIONS } from "../duckdb-engine";
import { parsePlainLiteral, splitLegacyOptions } from "../attach/legacy-options";
import { buildAttachSql, getenvName, isSecretOption, OPTION_NAME_RE, type OptionSpecInfo } from "../attach/options";
import { assignAliases, isValidAlias } from "./aliases";
import { catalogKind, validateWorkspaceFile, WORKSPACE_FORMAT, WORKSPACE_VERSION, type PortableCatalog, type PortableWorkspace } from "./spec";
import { withIds, type ImportWorkspace, type SecretNamesOf } from "./file";
import { newWorkspaceId, workspaceLabel, type Workspace } from "./store";

export const DUCKDB_SCRIPT_EXTENSION = ".sql";
/** Longer scripts are refused before tokenizing. */
const MAX_SCRIPT_CHARS = 256 * 1024;
const MAX_EXPR_CHARS = 2048;

const HEADER_NAME = "-- Cupola workspace: ";
const HEADER_ID = "-- Workspace id: ";

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

function installLine(name: "vgi" | "grainlift"): string {
  const ext = SHELL_EXTENSIONS.find((e) => e.name === name) ?? { name, source: "community" };
  return `${extensionInstallSql(ext)}; LOAD ${name};`;
}

/** Text safe inside a `--` comment: one line. */
function commentText(text: string): string {
  return text.replace(/[\r\n\u2028\u2029\u0085\v\f]+/g, " ").trim();
}

/** A secret's spec, so `buildAttachSql` emits getenv() for it whatever its
 *  name looks like. */
function secretSpec(name: string): OptionSpecInfo {
  return { name, description: "", duckdbType: "VARCHAR", castType: null, arrowType: "Utf8", required: false, secret: true };
}

/** The workspace as a script for the duckdb CLI. Only enabled catalogs are
 *  attached (a disabled one is named in a comment). Secrets are read from the
 *  environment; their names come from `secretNames` (by default none). */
export function workspaceToDuckdbScript(ws: Workspace, secretNames: SecretNamesOf = () => []): string {
  const enabled = ws.catalogs.filter((c) => c.enabled && c.catalogName && c.alias);
  const lines: string[] = [];
  lines.push(`${HEADER_NAME}${commentText(workspaceLabel(ws))}`);
  lines.push(`${HEADER_ID}${commentText(ws.id)}`);
  lines.push("-- Generated by Cupola. Run with: duckdb -init <this file>");

  const attaches: string[] = [];
  const envVars: string[] = [];
  const skipped: string[] = [];
  for (const c of ws.catalogs) {
    if (!enabled.includes(c)) {
      skipped.push(`--   ${quoteIdent(c.alias || c.catalogName || "catalog")}: ${c.enabled ? "never connected, so the server has not named it" : "disabled in this browser"}`);
      continue;
    }
    const secrets = secretNames(ws, c);
    const lower = new Set(secrets.map((s) => s.toLowerCase()));
    const options: Record<string, string> = {};
    for (const [name, value] of Object.entries(c.options)) if (!lower.has(name.toLowerCase())) options[name] = value;
    for (const name of secrets) if (OPTION_NAME_RE.test(name)) options[name] = "";
    const kind = catalogKind(c.url);
    if (kind === "grainlift" && c.target) options.target = c.target;
    if (c.dataVersionSpec) options.data_version_spec = c.dataVersionSpec;
    const specs = secrets.map(secretSpec);
    for (const name of Object.keys(options)) if (isSecretOption(name, specs)) envVars.push(getenvName(c.alias, name));
    if (c.rawOptions) attaches.push(`-- Not included for ${quoteIdent(c.alias)}: options not yet evaluated (${commentText(c.rawOptions)}).`);
    attaches.push(`${buildAttachSql({ kind, url: c.url, catalogName: c.catalogName, alias: c.alias, options, specs }, "cli")};`);
  }

  if (envVars.length) {
    lines.push("--", "-- Set these environment variables first:");
    for (const v of envVars) lines.push(`--   export ${v}=...`);
  }
  if (skipped.length) {
    lines.push("--", "-- Not attached:");
    lines.push(...skipped);
  }
  lines.push("");
  if (!enabled.length) {
    lines.push("-- This workspace has no catalog to attach.");
    return lines.join("\n") + "\n";
  }
  lines.push(installLine("vgi"));
  if (enabled.some((c) => catalogKind(c.url) === "grainlift")) lines.push(installLine("grainlift"));
  lines.push("", ...attaches, "");
  const def = enabled.find((c) => c.id === ws.defaultCatalogId) ?? enabled[0];
  lines.push(ws.defaultSchema ? `USE ${quoteIdent(def.alias)}.${quoteIdent(ws.defaultSchema)};` : `USE ${quoteIdent(def.alias)};`);
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Tokenizer
// ---------------------------------------------------------------------------

export type TokenType = "string" | "ident" | "qident" | "number" | "punct";

export interface Token {
  type: TokenType;
  /** Decoded value: a string's text, an identifier's name. */
  value: string;
  /** Source offsets. */
  start: number;
  end: number;
  line: number;
}

export class ScriptError extends Error {
  constructor(readonly line: number, message: string) {
    super(`Line ${line}: ${message}`);
  }
}

const PUNCT = new Set(["(", ")", "[", "]", "{", "}", ",", ";", ".", ":", "-", "+", "*", "/", "=", "<", ">", "!", "%", "|", "&", "^", "~", "?"]);
const OPEN: Record<string, string> = { "(": ")", "[": "]", "{": "}" };

/** Split SQL text into tokens. Handles `'…'` strings and `"…"` identifiers
 *  with doubled-quote escapes, `--` and `/* … *\/` comments, and checks that
 *  brackets balance. Anything it does not know (`$$` strings, backslashes) is
 *  an error rather than a guess. */
export function tokenize(text: string): Token[] {
  const tokens: Token[] = [];
  const stack: { close: string; line: number }[] = [];
  let line = 1;
  let i = 0;
  const n = text.length;
  while (i < n) {
    const c = text[i];
    if (c === "\n") { line++; i++; continue; }
    if (/\s/.test(c)) { i++; continue; }
    if (c === "-" && text[i + 1] === "-") {
      while (i < n && text[i] !== "\n") i++;
      continue;
    }
    if (c === "/" && text[i + 1] === "*") {
      const startLine = line;
      const end = text.indexOf("*/", i + 2);
      if (end < 0) throw new ScriptError(startLine, "a /* comment is never closed.");
      for (let k = i; k < end; k++) if (text[k] === "\n") line++;
      i = end + 2;
      continue;
    }
    if (c === "'" || c === '"') {
      const startLine = line;
      const start = i;
      let value = "";
      i++;
      for (;;) {
        if (i >= n) throw new ScriptError(startLine, c === "'" ? "a string is never closed (unbalanced ')." : "a quoted name is never closed (unbalanced \").");
        const ch = text[i];
        if (ch === c) {
          if (text[i + 1] === c) { value += c; i += 2; continue; }
          i++;
          break;
        }
        if (ch === "\n") line++;
        value += ch;
        i++;
      }
      tokens.push({ type: c === "'" ? "string" : "qident", value, start, end: i, line: startLine });
      continue;
    }
    if (/[A-Za-z_]/.test(c)) {
      const start = i;
      while (i < n && /[A-Za-z0-9_]/.test(text[i])) i++;
      tokens.push({ type: "ident", value: text.slice(start, i), start, end: i, line });
      continue;
    }
    if (/[0-9]/.test(c) || (c === "." && /[0-9]/.test(text[i + 1] ?? ""))) {
      const start = i;
      while (i < n && /[0-9.eE_]/.test(text[i])) {
        if ((text[i] === "e" || text[i] === "E") && /[+-]/.test(text[i + 1] ?? "")) i++;
        i++;
      }
      tokens.push({ type: "number", value: text.slice(start, i), start, end: i, line });
      continue;
    }
    if (PUNCT.has(c)) {
      if (c in OPEN) stack.push({ close: OPEN[c], line });
      else if (c === ")" || c === "]" || c === "}") {
        const open = stack.pop();
        if (!open || open.close !== c) throw new ScriptError(line, `unbalanced brackets: "${c}" closes nothing open.`);
      } else if (c === ";" && stack.length) {
        throw new ScriptError(stack[stack.length - 1].line, `a bracket opened here is not closed before the ";" on line ${line}.`);
      }
      // `::` is one token.
      if (c === ":" && text[i + 1] === ":") {
        tokens.push({ type: "punct", value: "::", start: i, end: i + 2, line });
        i += 2;
        continue;
      }
      tokens.push({ type: "punct", value: c, start: i, end: i + 1, line });
      i++;
      continue;
    }
    throw new ScriptError(line, `unexpected character ${JSON.stringify(c)}.`);
  }
  if (stack.length) throw new ScriptError(stack[stack.length - 1].line, "a bracket opened here is never closed.");
  return tokens;
}

/** Tokens back to SQL text: the source between adjacent tokens is kept when
 *  it is whitespace, and replaced by a space when it held a comment. */
function sourceOf(text: string, tokens: readonly Token[]): string {
  let out = "";
  tokens.forEach((t, i) => {
    if (i > 0) {
      const gap = text.slice(tokens[i - 1].end, t.start);
      out += /^\s*$/.test(gap) ? gap : " ";
    }
    out += text.slice(t.start, t.end);
  });
  return out.trim();
}

// ---------------------------------------------------------------------------
// Parser
// ---------------------------------------------------------------------------

export type ScriptParseResult =
  | { ok: true; workspace: ImportWorkspace; warnings: string[] }
  | { ok: false; errors: string[] };

interface Statement {
  tokens: Token[];
  line: number;
}

function splitStatements(tokens: readonly Token[]): Statement[] {
  const out: Statement[] = [];
  let current: Token[] = [];
  for (const t of tokens) {
    if (t.type === "punct" && t.value === ";") {
      if (current.length) out.push({ tokens: current, line: current[0].line });
      current = [];
    } else current.push(t);
  }
  if (current.length) out.push({ tokens: current, line: current[0].line });
  return out;
}

const isWord = (t: Token | undefined, word: string) => t?.type === "ident" && t.value.toLowerCase() === word;
const isPunct = (t: Token | undefined, p: string) => t?.type === "punct" && t.value === p;
const isName = (t: Token | undefined) => t?.type === "ident" || t?.type === "qident";

/** Functions an option expression may call: the constant allowlist of
 *  `legacy-options.ts`, plus CAST and type names that take parameters. The
 *  engine's AST check at connect time is still the gate; this refuses the
 *  obvious early, with a line number. */
const EXPR_CALLS = new Set(["list_value", "struct_pack", "map", "row", "cast", "decimal", "numeric", "struct", "union", "varchar"]);
const EXPR_FORBIDDEN = /^(?:select|from|with|pragma|copy|attach|detach|install|load|set|reset|call|getenv|query|query_table|export|import|create|drop|insert|update|delete|use)$|^read_/i;

function screenExpression(tokens: readonly Token[]): string | null {
  for (const [i, t] of tokens.entries()) {
    if (t.type === "ident") {
      if (EXPR_FORBIDDEN.test(t.value)) return `"${t.value}" is not allowed in an option value; only constants are.`;
      if (isPunct(tokens[i + 1], "(") && !EXPR_CALLS.has(t.value.toLowerCase())) return `"${t.value}(…)" is not allowed in an option value; only constants, casts and [list], {struct}, MAP and row(...) values are.`;
    }
    if (t.type === "qident") return "a quoted name is not an option value; use 'single quotes' for text.";
    if (t.type === "punct" && !["(", ")", "[", "]", "{", "}", ",", ".", ":", "::", "-", "+"].includes(t.value)) return `"${t.value}" is not allowed in an option value; only constants are.`;
  }
  return null;
}

/** `getenv('X')`, exactly: the variable name, else null. */
function getenvVar(tokens: readonly Token[]): string | null {
  if (tokens.length === 4 && isWord(tokens[0], "getenv") && isPunct(tokens[1], "(") && tokens[2].type === "string" && isPunct(tokens[3], ")")) return tokens[2].value;
  return null;
}

/** Built-in credentials Cupola's own sign-in supplies; never imported. */
const SIGN_IN_OPTIONS = new Set(["bearer_token", "oauth_refresh_token"]);

function fail(line: number, message: string): never {
  throw new ScriptError(line, message);
}

interface ParsedAttach {
  line: number;
  catalog: PortableCatalog;
  rawOptions: string[];
  secretNotes: Record<string, string>;
}

function parseAttach(text: string, st: Statement, warnings: string[]): ParsedAttach {
  const t = st.tokens;
  let i = 1;
  if (isWord(t[i], "or")) {
    if (!isWord(t[i + 1], "replace")) fail(t[i].line, "expected OR REPLACE.");
    i += 2;
  }
  if (isWord(t[i], "database")) i++;
  if (isWord(t[i], "if")) {
    if (!isWord(t[i + 1], "not") || !isWord(t[i + 2], "exists")) fail(t[i].line, "expected IF NOT EXISTS.");
    i += 3;
  }
  const pathTok = t[i];
  if (pathTok?.type !== "string") fail(pathTok?.line ?? st.line, "ATTACH must be followed by the catalog in 'single quotes'.");
  i++;
  if (isWord(t[i], "as")) i++;
  const aliasTok = t[i];
  if (!isName(aliasTok) || isPunct(aliasTok, "(")) fail(aliasTok?.line ?? pathTok.line, "ATTACH needs AS <name>: the alias the catalog is attached under.");
  const alias = aliasTok.value;
  if (!isValidAlias(alias)) fail(aliasTok.line, `"${alias}" is not a usable catalog alias (letters, digits and underscores; not memory, temp, system or main).`);
  i++;
  if (!isPunct(t[i], "(")) fail(t[i]?.line ?? aliasTok.line, "expected the option list: (TYPE vgi, LOCATION '…', …).");
  const openAt = i;
  // The matching close: the tokenizer has already checked balance.
  let depth = 0;
  let closeAt = -1;
  for (let k = openAt; k < t.length; k++) {
    if (t[k].type !== "punct") continue;
    if (t[k].value in OPEN) depth++;
    else if (t[k].value === ")" || t[k].value === "]" || t[k].value === "}") {
      depth--;
      if (depth === 0) { closeAt = k; break; }
    }
  }
  if (closeAt < 0) fail(t[openAt].line, "the option list is never closed.");
  if (closeAt !== t.length - 1) fail(t[closeAt + 1].line, `unexpected "${text.slice(t[closeAt + 1].start, t[closeAt + 1].end)}" after the option list; end the statement with ";".`);

  // Top-level groups of the option list.
  const groups: Token[][] = [];
  let group: Token[] = [];
  depth = 0;
  for (let k = openAt + 1; k < closeAt; k++) {
    const tok = t[k];
    if (tok.type === "punct" && tok.value in OPEN) depth++;
    else if (tok.type === "punct" && (tok.value === ")" || tok.value === "]" || tok.value === "}")) depth--;
    if (depth === 0 && isPunct(tok, ",")) {
      groups.push(group);
      group = [];
      continue;
    }
    group.push(tok);
  }
  groups.push(group);

  let type: string | null = null;
  let location: string | null = null;
  const options: Record<string, string> = {};
  const secrets: string[] = [];
  const secretNotes: Record<string, string> = {};
  const rawOptions: string[] = [];
  let target: string | undefined;
  let dataVersionSpec: string | undefined;
  const seen = new Set<string>();
  for (const g of groups) {
    if (!g.length) fail(t[openAt].line, "empty entry in the option list.");
    const line = g[0].line;
    const nameTok = g[0];
    if (!isName(nameTok)) fail(line, `expected an option name, found "${text.slice(nameTok.start, nameTok.end)}".`);
    const name = nameTok.value;
    if (!OPTION_NAME_RE.test(name)) fail(line, `"${name}" is not a valid option name.`);
    const lower = name.toLowerCase();
    if (seen.has(lower)) fail(line, `option "${name}" is given twice.`);
    seen.add(lower);
    const valueTokens = g.slice(1);
    const expr = sourceOf(text, valueTokens);
    if (lower === "type") {
      if (valueTokens.length !== 1 || !isName(valueTokens[0])) fail(line, "TYPE must be vgi or grainlift.");
      type = valueTokens[0].value.toLowerCase();
      if (type !== "vgi" && type !== "grainlift") fail(line, `TYPE ${valueTokens[0].value} is not supported; only vgi and grainlift catalogs can be imported.`);
      continue;
    }
    if (lower === "location") {
      if (valueTokens.length !== 1 || valueTokens[0].type !== "string") fail(line, "LOCATION must be a URL in 'single quotes'.");
      location = valueTokens[0].value;
      continue;
    }
    // The same parser as the legacy option text: it validates the name and
    // splits the value, and refuses what it cannot read.
    const split = splitLegacyOptions(valueTokens.length ? `${name} ${expr}` : name);
    if (split.problems.length || split.entries.length !== 1) fail(line, `${name}: ${split.problems[0]?.reason ?? "not a valid option."}`);
    const entry = split.entries[0];
    if (SIGN_IN_OPTIONS.has(lower)) {
      warnings.push(`Line ${line}: ${name} was not imported; Cupola's own sign-in supplies it.`);
      continue;
    }
    const envVar = getenvVar(valueTokens);
    if (envVar !== null) {
      secrets.push(name);
      secretNotes[name] = `read from the environment variable ${envVar} in the script`;
      continue;
    }
    if (valueTokens.some((v) => isWord(v, "getenv"))) fail(line, `${name}: getenv() must be the whole value, as getenv('NAME').`);
    const plain = parsePlainLiteral(entry.expr);
    if (isSecretOption(name)) {
      // A credential written into a script is not carried into the workspace.
      secrets.push(name);
      secretNotes[name] = "its value in the script was not imported";
      warnings.push(`Line ${line}: ${name} looks like a credential, so its value was not imported; enter it in this browser.`);
      continue;
    }
    if (lower === "target" || lower === "data_version_spec") {
      if (plain === null || valueTokens.length !== 1 || valueTokens[0].type !== "string") fail(line, `${name} must be text in 'single quotes'.`);
      if (lower === "target") target = plain!;
      else dataVersionSpec = plain!;
      continue;
    }
    if (plain !== null) {
      options[name] = plain;
      continue;
    }
    if (expr.length > MAX_EXPR_CHARS) fail(line, `${name}: the value is too long.`);
    const refusal = screenExpression(valueTokens);
    if (refusal) fail(line, `${name}: ${refusal}`);
    rawOptions.push(`${name} ${entry.expr}`);
  }
  if (!type) fail(st.line, "the option list needs TYPE vgi or TYPE grainlift.");
  let url: string;
  let catalogName: string;
  if (type === "grainlift") {
    if (location !== null) fail(st.line, "a grainlift ATTACH takes the gateway URL as its path, not LOCATION.");
    url = pathTok.value;
    if (catalogKind(url) !== "grainlift") fail(pathTok.line, "a grainlift ATTACH's path must be a grainlift:// URL.");
    if (!target) fail(st.line, "a grainlift ATTACH needs target '…'.");
    catalogName = target!;
  } else {
    if (location === null) fail(st.line, "a vgi ATTACH needs LOCATION '<server URL>'.");
    url = location!;
    if (catalogKind(url) === "grainlift") fail(st.line, "a grainlift URL needs TYPE grainlift.");
    catalogName = pathTok.value;
  }
  const catalog: PortableCatalog = {
    url,
    catalogName,
    alias,
    ...(Object.keys(options).length ? { options } : {}),
    ...(secrets.length ? { secrets } : {}),
    ...(target ? { target } : {}),
    ...(dataVersionSpec ? { dataVersionSpec } : {}),
  };
  return { line: st.line, catalog, rawOptions, secretNotes };
}

function parseInstallOrLoad(st: Statement): void {
  const t = st.tokens;
  const verb = t[0].value.toUpperCase();
  const name = t[1];
  if (!isName(name) || !["vgi", "grainlift"].includes(name.value.toLowerCase())) {
    throw new ScriptError(st.line, `${verb} is accepted only for the vgi and grainlift extensions.`);
  }
  let i = 2;
  if (verb === "INSTALL") {
    if (isWord(t[i], "from")) {
      if (!isName(t[i + 1]) && t[i + 1]?.type !== "string") throw new ScriptError(st.line, "expected a repository after FROM.");
      i += 2;
    }
    if (isWord(t[i], "version")) {
      if (t[i + 1]?.type !== "string") throw new ScriptError(st.line, "expected a version in 'single quotes'.");
      i += 2;
    }
  }
  if (i !== t.length) throw new ScriptError(t[i].line, `unexpected "${t[i].value}" in ${verb}.`);
}

function parseUse(st: Statement): { alias: string; schema?: string; line: number } {
  const t = st.tokens;
  if (!isName(t[1])) throw new ScriptError(st.line, "USE needs a catalog alias.");
  if (t.length === 2) return { alias: t[1].value, line: st.line };
  if (t.length === 4 && isPunct(t[2], ".") && isName(t[3])) return { alias: t[1].value, schema: t[3].value, line: st.line };
  throw new ScriptError(st.line, "USE takes <catalog> or <catalog>.<schema>.");
}

/** The header an export writes (`-- Cupola workspace:` / `-- Workspace id:`),
 *  read from the comment lines before the first statement only. */
function readHeader(text: string): { name?: string; id?: string } {
  const out: { name?: string; id?: string } = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) continue;
    if (!line.startsWith("--")) break;
    if (line.startsWith(HEADER_NAME)) out.name = line.slice(HEADER_NAME.length).trim();
    else if (line.startsWith(HEADER_ID)) out.id = line.slice(HEADER_ID.length).trim();
  }
  return out;
}

/** Read a DuckDB script into a workspace to import. All-or-nothing: any
 *  statement outside the accepted set fails the whole script, with every
 *  problem listed by line. */
export function parseDuckdbScript(text: string, newId: () => string = newWorkspaceId): ScriptParseResult {
  if (text.length > MAX_SCRIPT_CHARS) return { ok: false, errors: ["The script is too large to import."] };
  let tokens: Token[];
  try {
    tokens = tokenize(text);
  } catch (error) {
    return { ok: false, errors: [error instanceof Error ? error.message : String(error)] };
  }
  const errors: string[] = [];
  const warnings: string[] = [];
  const attaches: ParsedAttach[] = [];
  let use: { alias: string; schema?: string; line: number } | null = null;
  for (const st of splitStatements(tokens)) {
    try {
      const head = st.tokens[0];
      const verb = head.type === "ident" ? head.value.toLowerCase() : "";
      if (verb === "attach") attaches.push(parseAttach(text, st, warnings));
      else if (verb === "use") use = parseUse(st);
      else if (verb === "install" || verb === "load") parseInstallOrLoad(st);
      else throw new ScriptError(st.line, `only ATTACH, USE, and INSTALL/LOAD of vgi or grainlift can be imported; "${text.slice(head.start, head.end)}" is refused.`);
    } catch (error) {
      errors.push(error instanceof Error ? error.message : String(error));
    }
  }
  if (!errors.length && !attaches.length) errors.push("The script attaches no catalog: it needs at least one ATTACH … (TYPE vgi, …).");
  const aliases = new Map<string, number>();
  for (const a of attaches) {
    const key = a.catalog.alias!.toLowerCase();
    if (aliases.has(key)) errors.push(`Line ${a.line}: the alias "${a.catalog.alias}" is already used on line ${aliases.get(key)}.`);
    else aliases.set(key, a.line);
  }
  if (use && !aliases.has(use.alias.toLowerCase())) errors.push(`Line ${use.line}: USE names "${use.alias}", which the script does not attach.`);
  if (errors.length) return { ok: false, errors };

  const header = readHeader(text);
  const portable: PortableWorkspace = {
    ...(header.id ? { id: header.id } : {}),
    ...(header.name ? { name: header.name } : {}),
    catalogs: attaches.map((a) => a.catalog),
    ...(use?.schema ? { defaultSchema: use.schema } : {}),
  };
  // The same validator as a workspace file: URL schemes, lengths, limits.
  const checked = validateWorkspaceFile({ format: WORKSPACE_FORMAT, version: WORKSPACE_VERSION, workspaces: [portable] });
  if (!checked.ok) return { ok: false, errors: [checked.error] };
  warnings.push(...checked.warnings);
  const validated = checked.file.workspaces[0];
  const item = withIds(validated, [], newId);
  if (use) {
    const def = item.workspace.catalogs.find((c) => c.alias?.toLowerCase() === use!.alias.toLowerCase());
    if (def) item.workspace.defaultCatalogId = def.id;
  } else {
    item.workspace.defaultCatalogId = item.workspace.catalogs[0].id;
  }
  // A workspace name from a header that is not ours is just the label.
  if (!item.workspace.name) item.workspace.name = null;
  const rawOptions: Record<string, string> = {};
  const secretNotes: Record<string, Record<string, string>> = {};
  attaches.forEach((a, i) => {
    const id = item.workspace.catalogs[i].id;
    if (a.rawOptions.length) rawOptions[id] = a.rawOptions.join(", ");
    if (Object.keys(a.secretNotes).length) secretNotes[id] = a.secretNotes;
  });
  const { notes: aliasNotes } = assignAliases(item.workspace.catalogs);
  item.notes = [...warnings, ...aliasNotes];
  if (Object.keys(rawOptions).length) item.rawOptions = rawOptions;
  if (Object.keys(secretNotes).length) item.secretNotes = secretNotes;
  return { ok: true, workspace: item, warnings: item.notes };
}
